### ISSUE TITLE
Issue into documentation

### ISSUE THREAD

**Issue by jdnichollsc** [ionic-widget/ui-tag-input#10]
Hi man,

Please, fix the issue into the documentation.

`Add into your controller angular.module('app.controllers'...`
To
`Add into your controllers module angular.module('app.controllers'`

Regards, Nicholls

**Comment by tanhauhau** [comment]
Hi, do you want to submit a PR for this?

**Comment by jdnichollsc** [comment]
You can do it! Improve yourself! ;)
